### ISSUE TITLE
website dead

### ISSUE THREAD

**Issue by kelfink** [sazeracjs/sazerac#16]
Looks like the sazeracjs.com website leads to some gambling site?

**Comment by paulmelnikow** [comment]
Hey @mikec I'd be happy to help with this!

**Comment by paulmelnikow** [comment]
Hey @mikec, just thought I would reach out to follow up. Would you be up for taking on a co-maintainer here? I use this library regularly and would be happy to continue to contribute, including getting a new website set up.

**Comment by mikec** [comment]
@paulmelnikow that would be great! Glad you're getting some use out of the library. I'd be happy to add you as co-maintainer since I haven't really been keeping up with this lib.

**Comment by paulmelnikow** [comment]
Thanks! I'm @paulmelnikow on npmjs.

Any pref on where to move the website to? A couple options:

- sazerac.js.org via gh-pages and https://js.org/
- zeit now and a new domain

**Comment by mikec** [comment]
@paulmelnikow sorry I haven't looked at this in quiet some time :[ ... did you end up deploying the site? gh-pages / js.org would be awesome

**Comment by paulmelnikow** [comment]
Okay, I've just started the process with the gh-pages route.

I think the next step is for you to turn on GitHub pages here:
https://github.com/mikec/sazerac-site/settings

At that point we should start seeing the site at https://mikec.github.io/sazerac-site/

I did happen to register sazerac.dev a couple weeks ago, so how about we use that name? 😀I'll get the DNS pointing to GH pages, and then I think all that's left is to add the CNAME file in the repo.

**Comment by paulmelnikow** [comment]
I've added the CNAME file pointing to `sazerac.js.org`. Once GitHub Pages is turned on, I'll open a PR as described in step 4 at https://js.org/ and we should be good to go!

**Comment by paulmelnikow** [comment]
Hey @mikec I'm running into some issues because I'm not an admin on this project. What would you think about moving the code into an organization and making me an owner?

Alternatively, I think the next step is to turn on GitHub Pages support on the website repo:

https://github.com/mikec/sazerac-site/tree/gh-pages

Once it's working at https://mikec.github.io/sazerac-site I can create the CNAME on the js.org side.

**Comment by paulmelnikow** [comment]
Hey @mikec just wanted to follow up about this. What would you think about moving the code into an organization and making me an owner?

**Comment by paulmelnikow** [comment]
Hey @mikec, I wanted to touch base!

Would you be up to moving this code into an org and making me an owner? I'm happy to create the org if you'd like.

**Comment by mikec** [comment]
@paulmelnikow sorry for the delayed response. Yes, if you create the org I'll move this over. I probably won't be working on it, but may as well put us both as owners on the new org.

**Comment by paulmelnikow** [comment]
Sounds good. Thank you! I will take care of creating that today.

I emailed GitHub about claiming https://github.com/sazerac under their name squatting policy, but no dice, so I'll create sazeracjs, instead.

**Comment by paulmelnikow** [comment]
All set! https://github.com/orgs/sazeracjs

**Comment by mikec** [comment]
@paulmelnikow thanks! just transferred ownership

**Comment by paulmelnikow** [comment]
Thanks! Could you move the website and example repos too?

**Comment by mikec** [comment]
@paulmelnikow moved those over as well. Thanks for taking this over! can't wait to see the site back in action :)

**Comment by paulmelnikow** [comment]
My pleasure! Thanks for the transfer. I'm excited to carry it forward.

**Comment by paulmelnikow** [comment]
I've done the last step and hopefully the new DNS will be online within a couple days! js-org/js.org#3019

@mikec Could you add me to the npm package so I can do a release that updates the links? The website for sure, though also the repo link, which is pointing to the wrong repo right now. https://www.npmjs.com/~paulmelnikow

**Comment by mikec** [comment]
@paulmelnikow nice!! just added you to the npm package

**Comment by paulmelnikow** [comment]
And the website is live! https://sazerac.js.org/

**Comment by mikec** [comment]
@paulmelnikow that's awesome, thanks!!
